myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from tickets import views
from myapp.views import register, recover

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.app_url')),  # Se incluye el archivo de URLs de myapp
    path('tickets/', include('tickets.urls')), 
    path('registrarticket/', views.registrarticket, name='registrarticket'), # Se incluye el archivo de URLs de tickets
    path('eliminarticket/', views.eliminarticket, name='eliminarticket'),
    path('editarticket/<int:id>/', views.editarticket, name='editarticket'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
    path('recover/', recover, name='recover'),
   
]

myproject/tickets/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ticket_list, name='ticket_list'),
    path('registrarticket/', views.registrarticket), #recive el id no sirve para editar los datos y me envia a otra plantilla
    path('editarticket/<id>/', views.editarticket),
    path('eliminarticket/<id>', views.eliminarticket),
    # Otros patrones de URL para las vistas de tickets
]

myproject/myapp/models.py
from django.db import models
#librerias

class MyModel(models.Model):
    # Campos del modelo MyModel
    codigo_bien = models.CharField(max_length=50, verbose_name='Código Bien')
    codigo_anterior = models.CharField(max_length=50, verbose_name='Código Anterior', blank=True, null=True)
    codigo_provisional = models.CharField(max_length=50, verbose_name='Código Provisional', blank=True, null=True)
    codigo_nuevo = models.CharField(max_length=50, verbose_name='Código Nuevo', blank=True, null=True)
    nombre_bien = models.CharField(max_length=100, verbose_name='Nombre Bien')
    serie = models.CharField(max_length=50, verbose_name='Serie', blank=True, null=True)
    modelo = models.CharField(max_length=50, verbose_name='Modelo')
    marca = models.CharField(max_length=50, verbose_name='Marca')
    color = models.CharField(max_length=50, verbose_name='Color')
    material = models.CharField(max_length=50, verbose_name='Material')
    estado = models.CharField(max_length=50, verbose_name='Estado')
    ubicacion = models.CharField(max_length=100, verbose_name='Ubicación')
    cedula = models.CharField(max_length=20, verbose_name='Cédula')
    custodio_actual = models.CharField(max_length=150, verbose_name='Custodio Actual')
    observacion = models.TextField(verbose_name='Observación', blank=True, null=True)
    archivo = models.FileField(upload_to='archivos/', verbose_name='Archivo Adjunto', blank=True, null=True)
    estado_registro = models.BooleanField(default=True, verbose_name='Estado de Registro')
    codigo_tic = models.CharField(max_length=50, verbose_name='Código Tic', blank=True, null=True)


    def __str__(self):
        return self.codigo_bien

class CambioCustodio(models.Model):
    modelo_relacionado = models.ForeignKey(MyModel, on_delete=models.CASCADE)
    nuevo_custodio = models.CharField(max_length=150, verbose_name='Nuevo Custodio')
    cedula_nuevo_custodio = models.CharField(max_length=20, verbose_name='Cédula Nuevo Custodio')
    fecha_cambio = models.DateField(verbose_name='Fecha de Cambio')

    def __str__(self):
        return f"Cambio de custodio para {self.modelo_relacionado.nombre_bien} el {self.fecha_cambio}"


class Meta:
        permissions = [
            ("view_mymodel", "Can view MyModel"),
            ("change_mymodel", "Can change MyModel"),
            ("delete_mymodel", "Can delete MyModel"),
        ]

myproject/tickets/models.py
from django.db import models
from datetime import timedelta
from django.utils import timezone
from django.utils.timezone import now

class Ticket(models.Model):
    # llave primaria
    titulo = models.CharField(max_length=200, verbose_name='titulo')
    asunto = models.TextField(max_length=100, verbose_name='asunto')
    descripcion = models.TextField(max_length=200, verbose_name='descipcion')
    departamento = models.TextField(max_length=200, verbose_name='departamento')
    estado = models.CharField(max_length=200, verbose_name='estado')
    fecha = models.DateTimeField(default=now, verbose_name='fecha')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
   # Otros campos que puedas necesitar...

def __str__(self):
    texto = "{0} ({7})"
    return texto.formats(self.titulo, self.asunto, self.descripcion, self.departamento, self.estado, self.fecha) 

myproject/myapp/forms.py
from django import forms
from .models import MyModel, CambioCustodio
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import AuthenticationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        'invalid_login': "Por favor, introduzca un nombre de usuario y contraseña correctos. Por favor, note que ambos campos son sensibles a mayúsculas.",
        'inactive': "Esta cuenta está inactiva.",
    }


class LoginForm(forms.Form):
    username = forms.CharField(label="username", required=False)
    password = forms.CharField(label="password", widget=forms.PasswordInput, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Entrar'))


class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username','first_name','last_name','password1','password2']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('register','Register'))
    
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            viewers_group = Group.objects.get(name='viewers')
            user.groups.add(viewers_group)
            return User


class MyModelForm(forms.ModelForm):
    class Meta:
        model = MyModel
        fields = ['codigo_tic','codigo_bien', 'codigo_anterior', 'codigo_provisional', 'codigo_nuevo', 'nombre_bien', 
                  'serie', 'modelo', 'marca', 'color', 'material', 'estado', 'ubicacion', 'cedula', 
                  'custodio_actual', 'observacion', 'archivo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk is None:  # Si el registro no existe (es decir, estamos en la creación)
            # Si el registro no existe (es decir, estamos en la creación)
            for field_name in self.fields:
                if field_name != 'archivo':
                    self.fields[field_name].required = False



class CambioCustodioForm(forms.ModelForm):
    class Meta:
        model = CambioCustodio
        fields = ['nuevo_custodio', 'cedula_nuevo_custodio']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk is None:  # Si el registro no existe (es decir, estamos en la creación)
            # Si el registro no existe (es decir, estamos en la creación)
            for field_name in self.fields:
                self.fields[field_name].required = False

myproject/myapp/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import MyModel, CambioCustodio
from .forms import MyModelForm, CambioCustodioForm, CustomUserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from openpyxl import Workbook
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.models import Permission
from django.db import migrations
from reportlab.lib.units import inch
import pytz
from openpyxl.styles import Font, Alignment


def home(request):
    return render(request, 'registration/login.html')

def register(request):
    data = {
        'form': CustomUserCreationForm()
    }
    if request.method == 'POST':
        user_creation_form = CustomUserCreationForm(data=request.POST)
        if user_creation_form.is_valid():
            user = user_creation_form.save()
            user = authenticate(username=user_creation_form.cleaned_data['username'], password=user_creation_form.cleaned_data['password1'])
            if user is not None:
                login(request, user)
                messages.success(request, '¡Usuario registrado correctamente!')
                return redirect('register')

    return render(request, 'registration/register.html', data)


#Permisos required
@login_required
@permission_required('myapp.can_view_mymodel', raise_exception=True)
def model_detail(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    return render(request, 'model_detail.html', {'model': model})

@permission_required('myapp.can_view_mymodel', raise_exception=True)
def model_list(request):
    models = MyModel.objects.all()
    return render(request, 'model_list.html', {'models': models})

@login_required
@permission_required('myapp.can_view_mymodel', raise_exception=True)
def model_create(request):
    if request.method == 'POST':
        form = MyModelForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            for field_name, field_value in instance._dict_.items():
                if not field_value and field_name != 'id':
                    setattr(instance, field_name, 'VACÍO')
            instance.save()
            return redirect('model_list')
    else:
        form = MyModelForm()
    return render(request, 'model_form.html', {'form': form})

@login_required
@permission_required('myapp.can_view_mymodel', raise_exception=True)
def model_update(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    if request.method == 'POST':
        form = MyModelForm(request.POST, request.FILES, instance=model)
        cambio_form = CambioCustodioForm(request.POST)
        if form.is_valid() and cambio_form.is_valid():
            model = form.save(commit=False)
            if 'archivo' in request.FILES:
                model.archivo = request.FILES['archivo']
                model.save()

            cambio = model.cambiocustodio_set.first()
            if not cambio:
                cambio = CambioCustodio(modelo_relacionado=model)
            cambio.nuevo_custodio = cambio_form.cleaned_data['nuevo_custodio']
            cambio.cedula_nuevo_custodio = cambio_form.cleaned_data['cedula_nuevo_custodio']
            cambio.fecha_cambio = timezone.now()
            cambio.save()

            return redirect('model_list')
    else:
        form = MyModelForm(instance=model)
        cambio_form = CambioCustodioForm()

    return render(request, 'actualizar.html', {'form': form, 'cambio_custodio_form': cambio_form, 'model': model})

@login_required
@permission_required('myapp.can_view_mymodel', raise_exception=True)
def model_confirm_actualizar(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    if request.method == 'POST':
        form_data = request.session.get('form_data')
        if form_data:
            form = MyModelForm(form_data, instance=model)
            if form.is_valid():
                form.save()
                return redirect('model_list')
                
    else:
        form = MyModelForm(instance=model)
    return render(request, 'model_confirm_actualizar.html', {'form': form, 'model': model})

@login_required
@permission_required('myapp.can_view_mymodel', raise_exception=True)
def model_confirm_delete(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    return render(request, 'model_confirm_delete.html', {'model': model})

@login_required
@permission_required('myapp.can_view_mymodel', raise_exception=True)
def model_delete(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    if request.method == 'POST':
        model.estado_registro = False
        model.save()
        return redirect('model_list')
    return redirect('model_confirm_delete', pk=pk)

# @login_required llama al login antes de que entre a el siguiente metodo
@login_required
def dashboard(request):
    return render(request, 'registration/dashboard.html')

@login_required
def salir(request):
    logout(request)
    return redirect('/')
@login_required
def model_detail(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    return render(request, 'model_detail.html', {'model': model})
@login_required
def model_list(request):
    models = MyModel.objects.all()
    return render(request, 'model_list.html', {'models': models})
@login_required
def model_create(request):
    if request.method == 'POST':
        form = MyModelForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            for field_name, field_value in instance.__dict__.items():
                if not field_value and field_name != 'id':
                    setattr(instance, field_name, 'VACÍO')
            instance.save()
            return redirect('model_list')
    else:
        form = MyModelForm()
    return render(request, 'model_form.html', {'form': form})
@login_required
def model_update(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    if request.method == 'POST':
        form = MyModelForm(request.POST, request.FILES, instance=model)
        cambio_form = CambioCustodioForm(request.POST)
        if form.is_valid() and cambio_form.is_valid():
            model = form.save(commit=False)
            if 'archivo' in request.FILES:
                model.archivo = request.FILES['archivo']
                model.save()

            # Verificar si ya existe un objeto CambioCustodio para este modelo
            cambio = model.cambiocustodio_set.first()
            if not cambio:
                cambio = CambioCustodio(modelo_relacionado=model)
            cambio.nuevo_custodio = cambio_form.cleaned_data['nuevo_custodio']
            cambio.cedula_nuevo_custodio = cambio_form.cleaned_data['cedula_nuevo_custodio']
            cambio.fecha_cambio = timezone.now()  # Asigna la fecha actual
            cambio.save()

            return redirect('model_list')  # Redirigir a la lista de modelos después de la actualización
    else:
        form = MyModelForm(instance=model)
        cambio_form = CambioCustodioForm()

    return render(request, 'actualizar.html', {'form': form, 'cambio_custodio_form': cambio_form, 'model': model})


@login_required
def model_confirm_actualizar(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    if request.method == 'POST':
        # Guardar los cambios en la confirmación
        form_data = request.session.get('form_data')
        if form_data:
            form = MyModelForm(form_data, instance=model)
            if form.is_valid():
                form.save()
                return redirect('model_list')
                
    else:
        form = MyModelForm(instance=model)
    return render(request, 'model_confirm_actualizar.html', {'form': form, 'model': model})



@login_required
def model_confirm_delete(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    return render(request, 'model_confirm_delete.html', {'model': model})

@login_required
def model_delete(request, pk):
    model = get_object_or_404(MyModel, pk=pk)
    if request.method == 'POST':
        # Cambiar el estado_registro a False y guardar el objeto
        model.estado_registro = False
        model.save()
        return redirect('model_list')
    return redirect('model_confirm_delete', pk=pk)

#Exportacion de EXCEL
def export_to_excel(request):
   
    queryset1 = MyModel.objects.filter(estado_registro=True)
    queryset2 = CambioCustodio.objects.filter(modelo_relacionado__in=queryset1)

    # Crear un libro de trabajo y una hoja de trabajo
    wb = Workbook()
    ws = wb.active

    title = 'Reporte De Registros'
    ws.append([title])

    title_cell = ws.cell(row=1, column=1)
    title_cell.font = Font(size=25, bold=True)  # Negrita y tamaño de fuente
    ws.merge_cells('A1:R1')  # Combinar celdas para el título
    title_cell.alignment = Alignment(horizontal='center', vertical='center')  # Centrar texto horizontal y verticalmente
    total_columns = 18 
    additional_info = [
        'INSTITUTO NACIONAL DE METEOROLOGÍA E HIDROLOGÍA - INAMHI',
        'BIENES POR CUSTODIO',
        'REGISTRO DE CONSTATACIÓN FÍSICA DE BIENES 2024'
    ]
    start_row_for_info = 2
    for i, info in enumerate(additional_info, start=start_row_for_info):
        # Añadir una fila en blanco para que la información adicional se pueda colocar en varias celdas
        ws.append([''] * total_columns)
        info_cell = ws.cell(row=i, column=1)
        info_cell.value = info
        info_cell.font = Font(size=14, bold=True)
        info_cell.alignment = Alignment(horizontal='center', vertical='center')  # Centrar texto

myproject/myapp/templates/actualizar.html
{% load static %}
<!--Ingreso de el html actualizar-->
<!DOCTYPE html>
<html>
<head>
    <title>Actualizar Modelo</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style_actualizar.css' %}">
</head>
<body>
    <div class="container">
        <div class="header-image">
            <img src="../static/img/icono-inamhi.png" alt="">
        </div>
        <h1>Actualización</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Descripción</th>
                    </tr>
                </thead>
                <tbody>
                    {{ form.as_table }}
                    <!-- Agregar formulario para CambioCustodio -->
                    <tr>
                        <th></th>
                        <th>Cambio de Custodio</th>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            {{ cambio_custodio_form.as_table }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="button-container">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a href="{% url 'model_list' %}" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</body>
</html>

myproject/myapp/templates/eliminar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tabla con búsqueda y eliminación</title>
    <link rel="stylesheet" href="../static/styles/style_delete.css">
 
</head>

<body>
    <img src="../static/img/icono-inamhi.png" alt="">
    <div class="container">
        <h1>Tabla Con Búsqueda y Eliminación</h1>
        <input type="text" id="busqueda" placeholder="Buscar...">
        <table id="tabla">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Codigo Bien</th>
                    <th>Codigo Anterior</th>
                    <th>Codigo Provisional</th>
                    <th>Codigo Nuevo</th>
                    <th>Nombre Bien</th>
                    <th>Serie</th>
                    <th>Modelo</th>
                    <th>Marca</th>
                    <th>Color</th>
                    <th>Material</th>
                    <th>Estado</th>
                    <th>Ubicación</th>
                    <th>Cedula</th>
                    <th>Custodio Actual</th>
                    <th>Observación</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                

            </tbody>
        </table>
    </div>

    <script>
        function confirmarEliminar(button) {
            // Mostrar un mensaje de confirmación antes de eliminar
            if (confirm("¿Está seguro que desea eliminar este registro?")) {
                eliminarFila(button);
            }
        }

        function eliminarFila(button) {
            var fila = button.parentNode.parentNode;
            var id = fila.cells[0].innerText;
            fila.parentNode.removeChild(fila);
            var eliminados = JSON.parse(localStorage.getItem("eliminados")) || [];
            eliminados.push(id);
            localStorage.setItem("eliminados", JSON.stringify(eliminados));
        }

        document.addEventListener("DOMContentLoaded", function () {
            var eliminados = JSON.parse(localStorage.getItem("eliminados")) || [];
            eliminados.forEach(function (id) {
                var fila = document.querySelector("td:first-child").innerText;
                if (fila) {
                    fila.parentNode.style.display = "none";
                }
            });
        });

        document.getElementById("busqueda").addEventListener("keyup", function () {
            var texto = this.value.toLowerCase();
            var tabla = document.getElementById("tabla");
            var filas = tabla.getElementsByTagName("tr");
            for (var i = 0; i < filas.length; i++) {
                var textoFila = filas[i].textContent.toLowerCase();
                var id = filas[i].cells[0].innerText;
                if (textoFila.includes(texto) && !filaEliminada(id)) {
                    filas[i].style.display = "";
                } else {
                    filas[i].style.display = "none";
                }
            }
        });

        function filaEliminada(id) {
            var eliminados = JSON.parse(localStorage.getItem("eliminados")) || [];
            return eliminados.includes(id);
        }
    </script>
</body>
</html>

myproject/myapp/templates/model_confirm_actualizar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmacion</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Custom CSS for additional styling */
        body, html {
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #f8f9fa;
            background-color: #4C3DA8;
        }
        .container {
            max-width: 600px;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        .btn-actions {
            margin-top: 10px;
            margin-right: 10px;
        }
    
        .header-image {
            position: absolute;
            top: 20px;
            right: 20px;
            max-width: 100px;
        }
        .header-image img {
            width: 100%;
            height: auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header-image">
            <img src="../static/img/icono-inamhi.png" alt="">
        </div>
        <h1>Confirmar Actualización</h1>
        <p>¿Está seguro de que desea actualizar los datos?</p>
        <form method="post" action="{% url 'model_confirm_actualizar' model.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-actions">
                <i class="fas fa-check"></i> Sí, actualizar
            </button>
            <a href="{% url 'model_update' model.pk %}" class="btn btn-secondary btn-actions">
                <i class="fas fa-times"></i> Cancelar
            </a>
        </form>
    </div>
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</body>
</html>

myproject/myapp/templates/model_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar Eliminar</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static '/styles/confirm_delete.css' %}">

</head>
<body>
    
    <div class="container">
        <div class="header-image">
            <img src="../static/img/icono-inamhi.png" alt="">
        </div>
        <div class="card">
            <div class="card-body text-center">
                <div class="header-titles">
                    <h1 class="card-title"><i class="fas fa-exclamation-triangle mr-2"></i> Confirmar Eliminación</h1>
                </div>
                <p class="card-text">¿Está seguro de eliminar "{{ model.codigo_bien }}"?</p>
                <form action="{% url 'model_delete' pk=model.pk %}" method="post">
                    {% csrf_token %}
                    <div class="btn-group">
                        <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt mr-2"></i> Eliminar</button>
                        <a href="{% url 'model_list' %}" class="btn btn-secondary"><i class="fas fa-times mr-2"></i> Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Bootstrap JS (optional) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

myproject/myapp/templates/model_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if form.instance.pk %}Actualizar{% else %}Crear{% endif %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/styles/style_create.css">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>   
    <div class="header">
        <div class="header-image">
            <img src="../static/img/icono-inamhi.png" alt="Icono INAMHI">
        </div>
        <div class="header-titles">
            <h5>REPÚBLICA DEL ECUADOR</h5>
            <h5>INSTITUTO NACIONAL DE METEOROLOGIA E HIDROLOGIA -INAMHI BIENES POR CUSTODIO</h5>
            <h5>REGISTRO DE CONSTATACIÓN FÍSICA DE BIENES 2024</h5>
        </div>
    </div>

    <div class="container">            
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Descripción</th>
                        </tr>
                    </thead>
                    <tbody> 
                        <tr>
                            <td><label for="id_codigo_tic">Codigo Tic</label></td>
                            <td>{{ form.codigo_tic }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_codigo_bien">Código del Bien Esbye</label></td>
                            <td>{{ form.codigo_bien }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_codigo_anterior">Código Anterior</label></td>
                            <td>{{ form.codigo_anterior }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_codigo_provisional">Código Provisional</label></td>
                            <td>{{ form.codigo_provisional }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_codigo_nuevo">Código Nuevo</label></td>
                            <td>{{ form.codigo_nuevo }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_nombre_bien">Nombre del bien</label></td>
                            <td>{{ form.nombre_bien }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_serie">Serie</label></td>
                            <td>{{ form.serie }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_modelo">Modelo</label></td>
                            <td>{{ form.modelo }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_marca">Marca</label></td>
                            <td>{{ form.marca }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_color">Color</label></td>
                            <td>{{ form.color }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_material">Material</label></td>
                            <td>{{ form.material }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_estado">Estado</label></td>
                            <td>{{ form.estado }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_ubicacion">Ubicación</label></td>
                            <td>{{ form.ubicacion }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_cedula">Cédula Custodio</label></td>
                            <td>{{ form.cedula }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_custodio_actual">Custodio Actual</label></td>
                            <td>{{ form.custodio_actual }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_observacion">Observación</label></td>
                            <td>{{ form.observacion }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_archivo">Archivo Adjunto</label></td>
                            <td>{{ form.archivo }}</td>
                        </tr>
                        
                    </tbody>
                </table>
            </div>
            <div class="button-container">
                <button class="btn btn-save"><i class="fas fa-plus"></i> Guardar</button>
                <a href="{% url 'model_list' %}" class="btn btn-actions"><i class="fas fa-undo"></i> Regresar</a>
            </div>            
        </form>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>